### ISSUE TITLE
as a store owner i want to remove old recipes so that the app stays up to date with new recipes

### ISSUE THREAD

**Issue by ElliotScott0** [AgileGroup6/Agile-Project#93] opened 2023-01-26 13:59 UTC
# Description of issue
have a remove recipe page after the admin login

# Definition of done
- [ ] requirements for this issue to be marked as completed
- [ ] Follows the colour scheme
- [ ] Code is well commented
- [ ] Tests have been completed

**Comment by caydey** [comment] 2023-02-03 16:41
duplicate of #227

**Closed by caydey** 2023-02-03 16:41 UTC
Labels: Low Risk, Low Reward, Could, in progress, 5, Story
